---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          coverage: none
      - name: "Run PHP lint"
        run: "composer ci:php:lint"

  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-24.04
    needs: php-lint
    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          tools: composer:v2
          coverage: none
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v4
        with:
          key: "php${{ matrix.php-version }}
               -composer-${{ hashFiles('**/composer.lock') }}"
          path: ~/.composer/cache
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install composer dependencies"
        run: |
          composer install --no-ansi --no-interaction --no-progress
          composer show
      - name: "Run tests"
        run: "composer ci:tests:unit"

  functional-tests:
    name: "Functional tests"
    runs-on: ubuntu-24.04
    needs: php-lint
    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          tools: composer:v2
          coverage: none
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v4
        with:
          key: "php${{ matrix.php-version }}
               -composer-${{ hashFiles('**/composer.lock') }}"
          path: ~/.composer/cache
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install composer dependencies"
        run: |
          composer install --no-ansi --no-interaction --no-progress
          composer show
      - name: "Run tests"
        run: "composer ci:tests:functional"
